# Generated by Django 6.0.7 on 2026-07-17 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, help_text='Auto-generated from the title if left blank.', max_length=110, unique=True)),
                ('description', models.TextField(blank=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='games/thumbnails/')),
                ('play_url', models.URLField(blank=True, help_text="Where 'Play' should take the user. Leave blank to link to the game's detail page instead.")),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide from the launcher.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
    ]
